name: Test and Coverage Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test -- --coverage
        env:
          CI: true

      - name: Check coverage
        run: |
          # Calculate coverage percentage from the coverage summary
          COVERAGE=$(grep -Eo '"statements"\s*:\s*[0-9.]+' coverage/coverage-final.json | head -1 | grep -oE '[0-9.]+')
          echo "Current test coverage is $COVERAGE%"
          
          # Compare coverage with threshold (80%)
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "::error::Test coverage of $COVERAGE% is below the required 80% threshold"
            exit 1
          else
            echo "✅ Test coverage of $COVERAGE% meets the required threshold"
          fi

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/junit.xml
            **/test-results.xml
            **/test-results/**/*
            coverage/
          retention-days: 7
